### ISSUE TITLE
can you help me with this?

### ISSUE THREAD

**Issue by qwerasdzzz** [IBM/helayers-examples#2]
![image](https://github.com/IBM/helayers-examples/assets/129704553/8ca623c8-8539-4eca-910f-d247bbf70e9e)
A segmentation fault has occurred when I run the code in the mnist notebook,why would this happen?

**Comment by aehud** [comment]
Can you provide more details? Which version of pyhelayers are you using? Did you download the docker image or installed the pyhelayers library only? Where is the segmentation fault? On which machine are you running it?

**Comment by qwerasdzzz** [comment]
My pyhelayers version is 1.5.3.0,I didn't download the docker image.
![image](https://github.com/IBM/helayers-examples/assets/129704553/4834c2ac-ab12-4c8e-a8c7-711c5d57e656)
The fault occurred when I run the code in mnist notebook to this place,and I don't know why this wuold happen.
![image](https://github.com/IBM/helayers-examples/assets/129704553/03b0990d-4d0b-4b3c-8207-49495d47ed4b)

**Comment by qwerasdzzz** [comment]
![image](https://github.com/IBM/helayers-examples/assets/129704553/1b62a8bf-b1f0-40c6-aa3a-3bdb6a51e794)

**Comment by aehud** [comment]
Thanks. These screen shots you attached seem to be warnings. I don't think they are related. Can you provide a screen shot of the segmentation fault?
Also, a common problem is memory issues. How much memory you have on the machine you are running this demo?
Do other demos work ok? E.g., demo 02_NeuralNetwork_fraud_detection or 01_FHE_basics ?

**Comment by qwerasdzzz** [comment]
![c5080c03edfe866bd8c5b391b690810](https://github.com/IBM/helayers-examples/assets/129704553/d848965e-4e11-4bff-9b97-f26fb9e51db9)
This is the chinese meaning of segmentation fault.It means segmentation fault(core dumped).After the code runs, there is only this one error message, no more prompts.My machine has 64 gigabytes of memory.Other demos work ok.

**Comment by qwerasdzzz** [comment]
I have one more question. If the tile tensors are used  in this mnist notebook.

**Comment by aehud** [comment]
Yes, tile tensors are used 'under the hood' whenever you load a neural network model or other models. They are used to represent the tensors that run through the network and the network weights.

Regarding the error:
* Memory is still a suspect. Can you try another machine with more memory? Or perhaps check how much free memory you have on that machine? Perhaps not all 64GB of memory are free for the demo?
* Can you provide more information on machine? Type of hardware, os, etc...
* Can you add `print(profile)` before the crashing line `context = pyhelayers.HeModel.create_context(profile)`? Perhaps something is unusual in the object being passed to `create_context`.

**Comment by qwerasdzzz** [comment]
Thanks for your help,I run it on docker and it works ok.
